services:
  app:
    container_name: diamond-app
    image: diamond-app:latest
    ports:
      - '80:3001'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
