services:
  client:
    container_name: random-client
    build:
      context: .
      dockerfile: ./client/Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - ./client/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  backend:
    container_name: random-backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    depends_on:
      - db
    ports:
      - '3001:3001'
    volumes:
      - ./backend/:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=diamondapp
  db:
    container_name: random-db
    image: postgres:14-alpine
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=diamondapp
  # static-server:
  #   container_name: random-static-server
  #   build:
  #     context: .
  #     dockerfile: ./static-server/Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./client/build/:/frontend-static
  #     - ./static-server/:/app
  #     - /app/node_modules
  #   environment:
  #     - ENV_VAR:development
volumes:
  db:
    driver: local