FROM node:20.17.0

WORKDIR /app

COPY ./backend/* .

RUN npm install -g nodemon
RUN npm install -g ts-node
RUN npm install
RUN npx prisma generate

EXPOSE 3000

CMD [ "npm","run","dev" ]
#CMD tail -f /dev/null