on:
  push:
    branches:
    - master

jobs:
  deploy_ec2:
    name: Build and deploy to ec2 instance
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and push to docker hub
      id: build
      uses: cloudposse/github-action-docker-build-push@main
      with:
        file: Dockerfile.production
        image_name: coraxo/diamond-app
        registry: registry.hub.docker.com
        organization: "${{ github.event.repository.owner.login }}"
        repository: "${{ github.event.repository.name }}"
        login: "${{ secrets.DOCKER_LOGIN }}"
        password: "${{ secrets.DOCKER_PASSWORD }}"
        platforms: linux/amd64,linux/arm64

    - name: Deploy to ec2 instance
      shell: bash
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H "${{ secrets.EC2_URL }}" >> ~/.ssh/known_hosts
        ssh -o StrictHostKeyChecking=no "${{ secrets.EC2_USERNAME }}"@"${{ secrets.EC2_URL  }}" "cd diamond-app && ./deploy_prod.sh"

    outputs:
      image: ${{ steps.build.outputs.image }}
      tag: ${{ steps.build.outputs.tag }}